#!/bin/bash
cd ./
node ./iOS_Cookie.js
node ./jdSgmhShareCodes.js
node ./jd_Last_Week_income.js
node ./jd_api_test.js
node ./jd_bean_box.js
node ./jd_bean_change.js
node ./jd_bean_change_diy.js
node ./jd_bean_sign.js
node ./jd_bookshop.js
node ./jd_cash.js
node ./jd_cfd_game.js
node ./jd_cfd_shell.js
node ./jd_cfd_stock.js
node ./jd_club_lottery.js
node ./jd_deleteCart.js
node ./jd_dreamFactory.js
node ./jd_dreamFactory_help.js
node ./jd_family.js
node ./jd_foodRunning.js
node ./jd_fruit.js
node ./jd_getUp.js
node ./jd_gold_creator.js
node ./jd_health2.js
node ./jd_health_collect.js
node ./jd_ifanli.js
node ./jd_jdfactory.js
node ./jd_jin_tie.js
node ./jd_joy_park.js
node ./jd_jxbox.js
node ./jd_jxgc_stock.js
node ./jd_jxnnfls.js
node ./jd_kd.js
node ./jd_live.js
node ./jd_lotteryMachine.js
node ./jd_moneyTree.js
node ./jd_nzmh.js
node ./jd_pet.js
node ./jd_pigPet.js
node ./jd_plantBean.js
node ./jd_productZ4Brand.js
node ./jd_qq_pasture.js
node ./jd_sgmh.js
node ./jd_shop_sign.js
node ./jd_speed_redpocke.js
node ./jd_speed_sign.js
node ./jd_superMarket.js
node ./jd_track.js
node ./jd_unsubscribe.js
node ./jd_wxFans.js
node ./jd_xiaolongfan.js
node ./jd_yili_cow.js
