name: JDScripts
on:
  schedule:
    - cron: 30 15 * * *
  watch:
    types: started
env:
  TZ: Asia/Shanghai
  JD_COOKIE: ${{ secrets.CookieJDs }}
  BARK_PUSH: ${{ secrets.BARK }}
jobs:
  build:
    runs-on: Ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo npm install -g typescript
        sudo apt-get install wget
        sudo apt install rename
    - name: Update JDScripts
      run: |
        echo "========= 开始备份脚本 ========="
        cp -rf ./utils ./backup/utils
        cp -f ./*_*.ts ./backup/
        cp -f ./*_*.js ./backup/
        cp -f ./*_*.py ./backup/
        echo "========= 开始清空脚本 ========="
        shopt -s extglob
        rm -rf !(backup|README.md)
        shopt -u extglob
        echo "========= 开始下载curtinlv的脚本 ========="
        git clone https://github.com/curtinlv/JD-Script.git ./curtinlv
        find ./curtinlv/ -name "*py" -type f -exec cp {} ./ \;
        rm -rf ./curtinlv
        echo "========= 开始下载start的脚本 ========="
        git clone -b main https://github.com/star261/jd.git ./star
        cp -rf ./star/scripts/*_*.js ./
        rm -rf ./star
        echo "========= 开始下载JDHelloWorld的脚本 ========="
        git clone https://github.com/JDHelloWorld/jd_scripts.git ./JDHelloWorld
        cp -rf ./JDHelloWorld/utils ./utils
        cp -f ./JDHelloWorld/*_*.ts ./
        cp -f ./JDHelloWorld/*_*.js ./
        cp -f ./JDHelloWorld/package.json ./
        rm -rf ./JDHelloWorld
        echo "========= 开始下载单文件脚本 ========="
        wget -N https://github.com/yangtingxiao/QuantumultX/raw/master/scripts/jd/jd_lotteryMachine.js
        wget -N https://github.com/NobyDa/Script/raw/master/JD-DailyBonus/JD_DailyBonus.js
        wget -N https://github.com/jiulan/platypus/raw/main/scripts/jd_shop_sign.js
        echo "========= 开始更改前缀 ========="
        rename -f 's/^js_/jd_js/' *
        rename -f 's/^jd_fan/jd_wxFans/' *
        rename -f 's/^jx_/jd_jx/' *
        rename -f 's/^gua_/jd_gua/' *
        rename -f 's/^star_/jd_star/' *
        rename -f 's/^jddj/jd_dj/' *
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Automatic update via GitHub：$(date +"%Y-%m-%d %H:%M:%S")"
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: master
